### ISSUE TITLE
Sim City missing towns

### ISSUE THREAD

**Issue by Warzyw647** [vcmi-mods/warzyw-templates#24]
As of 1.5.6 not all towns are generated on the Sim City template due to too many obstacles.
Each of the 8 players' starting zones should have 1 player's town with fort and 9 neutral towns without fort, all from the same faction.
The middle zone should have 20 neutral towns with fort.
This used to work in some earlier VCMI versions, but then broke.
Try to fix this by playing around with zone sizes, zone filling and other template parameters.
Or perhaps play around with modding obstacles or some game config settings and similar stuff.

**Comment by dydzio0614** [comment]
I would report it to VCMI repo rather than mod

**Comment by Warzyw647** [comment]
I've figured out a workaround: adding 3 intervals of value 10 and density 30 to each zone or something like that makes the problem go away. I'll add a PR with that once the PR with Refugee Bank is closed (most likely merged, unless the town's author has something against it)
Will report the 3 smaller problems found while fixing that to the main repo.

**Comment by Warzyw647** [comment]
Implemented a workaround in https://github.com/vcmi-mods/warzyw-templates/pull/26
Issue added to the main vcmi repo
